services:
  redis:
    image: redis:7.2.10
    container_name: redis_s3
    restart: always

  postgresql:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  fastapi:
    container_name: fastapi_ws
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - postgresql
      - redis
    environment:
      PG_USER: admin
      PG_PASSWORD: root
      PG_HOST: postgresql
      PG_PORT: 5432
      PG_DB: test_db
      DATABASE_URL: postgresql+asyncpg://admin:root@postgresql:5432/test_db
      REDIS_URL: redis://redis:6379/1
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped

volumes:
  postgres-data:
