"""first migration

Revision ID: 204e427f20d6
Revises: f380e8ae1e41
Create Date: 2025-08-30 21:34:44.111232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204e427f20d6'
down_revision: Union[str, Sequence[str], None] = 'f380e8ae1e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_user_id'), 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_user_id'), 'user', type_='unique')
    # ### end Alembic commands ###
